### ISSUE TITLE
Fix destructor parametricity

### ISSUE THREAD

**Issue by apasel422** [apasel422/ref_count#3]
If rust-lang/rfcs#1327 is accepted, change the `Drop` impls from
```rust
#[unsafe_destructor_blind_to_params]
fn drop(&mut self) { ... }
```
to
```rust
#[unsafe_destructor_blind_to(T)]
fn drop(&mut self) { ... }
```
The current use of the first attribute is technically incorrect, as the destructor does in fact call methods on `C` through its `RefCount` bound, but it does not now nor should it ever call methods on `T` (other than `drop`). I think the current usage is nonetheless OK, because `C: 'static` and because `RefCount` is only implemented internally on two known types.

**Comment by arielb1** [comment]
You don't really need this - `unsafe_destructor_blind_to(T)` would only give you `C: 's`, which is already implied by `C: 'static`.

**Comment by apasel422** [comment]
I thought so, but wasn't sure. Thanks!
